config/routes.rb
Stockwatcher::Application.routes.draw do

  devise_for :users

  root 'welcome#index'

  resources :watches, :except => [:show]

  get 'lookup/stocks' => 'watches#stocks_json'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :watch
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :stock

  require 'csv'

  class << self

  	# Retrieve current pricing for all stocks in the stocks table, and
    # put it in the quotes table
	  def update_prices
	  	stocks = Stock.all.map { |s| s.code + '.nz' }.join(',') # XRO.nz,WHS.nz etc
	  	url = URI.parse("http://download.finance.yahoo.com/d/quotes.csv?s=#{stocks}&f=sl1t1d1p")
		  req = Net::HTTP::Get.new(url.to_s)
		  res = Net::HTTP.start(url.host, url.port) { |http| http.request(req) }

      puts res.body
  		quotes = CSV.parse(res.body)

  		quotes.each { |quote| update_price quote }
    end

    def update_price(quote)
      code = quote[0].split('.')[0] # Remove suffix, e.g. 'XRO.NZ' => 'XRO'
      price = quote[1]
      last_trade_time = DateTime.strptime("#{quote[3]} #{quote[2]}", '%m/%d/%Y %H:%M%P')
      last_trade_time = ActiveSupport::TimeZone['Auckland'].local_to_utc(last_trade_time)
      prev_close = quote[4]
      Quote.new(:stock => Stock.find_by_code(code), :price => price,
                :prev_close => prev_close, :last_trade_time => last_trade_time).save
    end

	  def check_watches
	    Watch.all.each do |watch|
        check_watch(watch)
      end
    end

    def check_watch(watch)
      quote = watch.stock.latest_quote

      if(!quote) then
        puts "No quotes found for #{watch.stock.code}"
        return
      end

      daily_diff = watch.stock.daily_diff

      puts <<-eos
          \nChecking watch on '#{watch.stock.code}' for user '#{watch.user.email}'
          Yesterday's close: $#{sprintf('%0.2f', quote.prev_close)}
          Latest quote: $#{sprintf('%0.2f', quote.price)} at #{quote.created_at.to_s} [ID: #{quote.id}]
          Last Trade Time: #{quote.last_trade_time.to_s}
          Difference: $#{sprintf('%0.2f', daily_diff.diff)}
          Change: #{sprintf('%0.2f', daily_diff.percent_change)}%
          Threshold: #{sprintf('%0.2f', watch.threshold)}%
      eos

      if daily_diff.percent_change.abs > watch.threshold then
        # Cheap hack - the stock market is never open for more than 16 hours
        if Alert.where("watch_id = ? and created_at > current_timestamp - interval '16 hours'", watch.id).exists? then
          puts 'Threshold exceeded; not sending alert as alert already sent within 16 hours'
        elsif quote.last_trade_time + 1.hours < Time.now
          puts 'Threshold exceeded; not sending alert as over one hour has passed since the stock was traded'
        else
          puts "Threshold exceeded; sending alert\n"
          if AlertMailer.stock_alert(watch, daily_diff).deliver_now then
            Alert.new(:watch => watch).save
          end
        end
      else
        puts 'Threshold not exceeded'
      end

    end
	end
end

app/models/quote_diff.rb
class QuoteDiff

  attr_accessor :quote

  def initialize(_quote)
    @quote = _quote
  end

  def diff
    @quote.price - @quote.prev_close
  end

  def percent_change
    (diff / @quote.prev_close) * 100.0
  end

  def direction
    case
      when diff > 0
        '+'
      when diff < 0
        '-'
      else
        ''
    end
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base

  def label
    "#{code} [#{name}]"
  end

  # The most recent quote for this stock
  def latest_quote
    Quote.where(
      'stock_id = ? and created_at = (select max(created_at) from quotes where stock_id = ?)',
      id, id).first or raise "Could not find the latest quote for #{code}"
  end

  def daily_diff
    QuoteDiff.new latest_quote
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
  	"#{first_name} #{last_name}"
  end
end

app/models/watch.rb
class Watch < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock

  validates :stock, presence: true
  validates :threshold, presence: true, :numericality => { :greater_than => 0}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    watches_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) {
     |u| u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name) }
    devise_parameter_sanitizer.for(:sign_up) {
     |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name) }
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_watch, only: [:show, :edit, :update, :destroy]
  before_action :get_stocks, only: [:new, :edit, :create, :update]
  before_filter :authenticate_user!

  # GET /watches
  def index
    @watches = Watch.where(:user => current_user)
  end

  # GET /watches/new
  def new
    @watch = Watch.new
  end

  # GET /watches/1/edit
  def edit
    if @watch.user != current_user then
      raise ActiveRecord::RecordNotFound
    end
  end

  # POST /watches
  def create
    @watch = Watch.new(watch_params)
    @watch.user = current_user

    if @watch.save
      flash.notice = "You're now watching #{@watch.stock.code}"
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /watches/1
  def update
    if @watch.user != current_user then
      raise ActiveRecord::RecordNotFound
    end
    if @watch.update(watch_params)
      flash.notice = "You've successfully updated your watch"
      redirect_to action: 'index'
    else
      render action: 'edit' 
    end
  end

  # DELETE /watches/1
  def destroy
    @watch.destroy
    redirect_to watches_url
  end

  def stocks_json
    render json: Stock.select('id, code, name')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watch
      @watch = Watch.find(params[:id])
    end

    def get_stocks
      @stocks = Stock.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watch_params
      params.require(:watch).permit(:stock_id,:threshold)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def direction_to_color(direction)
    case direction
      when '+'
        'green'
      when '-'
        'red'
      else
        'black'
    end
  end
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright &copy; 2014 <a href="http://www.linkedin.com/pub/george-dewar/2b/68a/627">George Dewar</a>; All rights reserved</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Stock Watcher', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.full_name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/users/edit">My account</a></li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if current_user %>

<li><a href="/watches">My Watches</a></li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stock Watcher :: Set up custom alerts for stocks on the NZX" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Stock Watcher lets you
    specify stocks on the NZX that you're interested in, and watches them for you, alerting you if your criteria are
    met." %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<header>
    <%= render 'layouts/navigation' %>
</header>
<main role="main">
    <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
    </div>
</main>
<footer>
    <div class="container">
        <%= render 'layouts/footer' %>
    </div>
</footer>

<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47969936-1', 'stockwatcher.co.nz');
  ga('send', 'pageview');

</script>
<% end %>

</body>
</html>

app/views/watches/_form.html.erb
<%= bootstrap_form_for(@watch) do |f| %>
  <% if @watch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@watch.errors.count, "error") %> prohibited this watch from being saved:</h2>

      <ul>
      <% @watch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :stock_id, 'Stock' %>
  <%= collection_select(:watch, :stock_id, @stocks, :id, :label, {:prompt => true}, :class => 'form-control') %>
  <%= f.text_field :threshold, :label => 'Threshold (percentage change in either direction from yesterday\'s close to trigger an alert)' %>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to 'Back', watches_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/watches/edit.html.erb
<h1>Edit watch</h1>

<%= render 'form' %>

app/views/watches/index.html.erb
<h1>Stocks I'm watching</h1>

<% if @watches.empty? %>
  <p>You don't have any watches! Click the button below to watch a stock.</p>
  <p><%= link_to 'Watch a stock', new_watch_path, class: "btn btn-primary" %></p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Threshold</th>
        <th>Current Price</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @watches.each do |watch| %>
        <tr>
        	<td><%= watch.stock.code %></td>
        	<td><%= watch.stock.name %></td>
        	<td>+/- <%= number_to_percentage(watch.threshold, precision: 2) %> from prev close</td>
          <td><%= number_to_currency(watch.stock.latest_quote.price) %>
            <span style="color: <%= direction_to_color(watch.stock.daily_diff.direction) %>;">
              (<% if watch.stock.daily_diff.diff == 0 then %>no change<% else %>
                <%= watch.stock.daily_diff.direction %><%= number_to_currency(watch.stock.daily_diff.diff.abs) %> /
                <%= watch.stock.daily_diff.direction %><%= number_to_percentage(watch.stock.daily_diff.percent_change.abs, precision: 2) %>
              <% end %>)
            </span>
            <a href="https://www.nzx.com/markets/NZSX/securities/<%= watch.stock.code %>">more</a>
          </td>
          <td>
            <%= link_to 'Edit', edit_watch_path(watch) %> | 
            <%= link_to 'Remove', watch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p><%= link_to 'Watch another stock', new_watch_path, class: "btn btn-primary" %></p>
<% end %>

app/views/watches/new.html.erb
<h1>New watch</h1>

<%= render 'form' %>

app/views/watches/show.html.erb
<%= link_to 'Edit', edit_watch_path(@watch) %> |
<%= link_to 'Back', watches_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Stock Watcher</h1>

<p>Stock Watcher lets you specify stocks on the NZX that you're interested in, and 
watches them for you. You can set a threshold (a percentage of movement from the previous 
day's close), and if this is exceeded Stock Watcher will send you an email notification.</p>

<p>With Stock Watcher, you'll know when there's a sudden movement in the market price of 
one of your stocks so you can observe more closely, or act as you see fit.</p>

<p>Stock Watcher checks prices every 10 minutes at the moment, and prices are delayed by 
20 minutes, but I am working on speeding this up. You will be notified as soon as your 
alert triggers.</p>

<p><strong>Please be aware</strong> that this tool is in the early stages of development, and may not work 
correctly. Use it at your own risk, and do not rely on the information provided by Stock 
Watcher for decision making.</p>

<% if current_user %>
	<p><%= link_to "Go to my watches", watches_path %></p>
<% else %>
	<p>To get started, <%= link_to "create an account", new_registration_path('user') %> 
	or <%= link_to "sign in", new_session_path('user') %> if you already have one.</p>
<% end %>